version: '3'
services:
  graph-db:
    container_name: graphdb
    image: ontotext/graphdb:10.0.2
    restart: unless-stopped
    ports:
     - 7200:7200
     - 7300:7300
    environment:
     GDB_JAVA_OPTS: >-
      -Xmx2g -Xms1g
      -Dgraphdb.home=/opt/graphdb/home
      -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
      -Dgraphdb.workbench.cors.enable=true
      -Denable-context-index=true
      -Dentity-pool-implementation=transactional
      -Dhealth.max.query.time.seconds=60
      -Dgraphdb.append.request.id.headers=true
      -Dreuse.vars.in.subselects=true
      -Dgraphdb.external-url=https://d4c.linkeddata.es/rdf
    volumes:
     - ./graphdb-data:/opt/graphdb/home
  helio:
    container_name: helio
    image: librairy/helio:0.3
    ports:
     - 8002:8080
    environment:
      - SERVER_PORT=8080 
      - SERVER_ADDRESS=0.0.0.0 
      - SERVER_USE-FORWARD-HEADERS=true